#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
    {
      "id":"urn:ngsi-ld:Store:001","type":"Store",
      "address":{"type":"PostalAddress","value":{"streetAddress":"Carrer del Serpis 1","addressRegion":"Valencia","addressLocality":"Valencia","postalCode":"46022"}},
      "location":{"type":"geo:json","value":{"type":"Point","coordinates":[-0.358836,39.474344]}},
      "name":{"type":"Text","value":"Café del Sol"},
      "temperature": { "type": "Number","value": 16},
      "relativeHumidity": {"type": "Number","value": 30}
    },
    {
      "id":"urn:ngsi-ld:Store:002","type":"Store",
      "address":{"type":"PostalAddress","value":{"streetAddress":"Avinguda dels Tarongers 2","addressRegion":"Valencia","addressLocality":"Valencia","postalCode":"46021"}},
      "location":{"type":"geo:json","value":{"type":"Point","coordinates":[-0.3595,39.473]}},
      "name":{"type":"Text","value":"La Taza Alegre"}
    },
    {
      "id":"urn:ngsi-ld:Store:003","type":"Store",
      "address":{"type":"PostalAddress","value":{"streetAddress":"Carrer de Ramon Llull 3","addressRegion":"Valencia","addressLocality":"Valencia","postalCode":"46022"}},
      "location":{"type":"geo:json","value":{"type":"Point","coordinates":[-0.359,39.4725]}},
      "name":{"type":"Text","value":"El Rincón del Café"}
    },
    {
      "id":"urn:ngsi-ld:Store:004","type":"Store",
      "address":{"type":"PostalAddress","value":{"streetAddress":"Avinguda de Blasco Ibáñez 4","addressRegion":"Valencia","addressLocality":"Valencia","postalCode":"46010"}},
      "location":{"type":"geo:json","value":{"type":"Point","coordinates":[-0.3592,39.4738]}},
      "name":{"type":"Text","value":"Sabores de España"}
    }
  ]
}'


#
# Add Weather and Twitter Responses for Store 1 using random values
#
curl -s -o /dev/null -X POST \
  http://orion:1026/v2/registrations \
  -H 'Content-Type: application/json' \
  -d '{
   "description": "Weather Conditions",   
   "dataProvided": {
     "entities": [
       {
         "id" : "urn:ngsi-ld:Store:001",
         "type": "Store"
       }
     ],
     "attrs": [
      "temperature", "relativeHumidity"
    ]
   },
   "provider": {
     "http": {
       "url": "http://context-provider:3000/proxy/v1/random/weatherConditions"
     },
     "legacyForwarding": true
   },
   "status": "active"
}'

curl -s -o /dev/null -X POST \
  http://orion:1026/v2/registrations \
  -H 'Content-Type: application/json' \
  -d '{
   "description": "Tweeting Cat Facts",
   "dataProvided": {
     "entities": [
       {
         "id" : "urn:ngsi-ld:Store:001",
         "type": "Store"
       }
     ],
     "attrs": [
      "tweets"
    ]
   },
   "provider": {
     "http": {
       "url": "http://context-provider:3000/proxy/v1/catfacts/tweets"
     },
     "legacyForwarding": true
   },
   "status": "active"
}'


# Add Weather and Twitter Responses for Store 2 using real sources
#
 curl -s -o /dev/null -X POST \
   'http://orion:1026/v2/registrations' \
   -H 'Content-Type: application/json' \
   -d '{
   "description": "Store:002 - Real Temperature and Humidity",
   "dataProvided": {
     "entities": [
       {
         "id": "urn:ngsi-ld:Store:002",
         "type": "Store"
       }
     ],
     "attrs": [
       "temperature",
       "relativeHumidity"
     ]
   },
   "provider": {
     "http": {
       "url": "http://context-provider:3000/proxy/weather/number/temperature:temp,relativeHumidity:humidity/berlin%2cde"
     },
      "legacyForwarding": true
   }
 }'

# curl -s -o /dev/null -X POST \
#   'http://orion:1026/v2/registrations' \
#   -H 'Content-Type: application/json' \
#   -d '{
#   "description": "Store:002 Real Tweets",
#   "dataProvided": {
#     "entities": [
#       {
#         "id": "urn:ngsi-ld:Store:002",
#         "type": "Store"
#       }
#     ],
#     "attrs": [
#       "tweets"
#     ]
#   },
#   "provider": {
#     "http": {
#       "url": "http://context-provider:3000/proxy/twitter/list/tweets:text/FIWARE"
#     },
#      "legacyForwarding": true
#   }
# }'

#
# Create a series of Shelf Entities and place the in each Store.
# Each shelf is designed to hold one product.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
	{
  		"id":"urn:ngsi-ld:Shelf:unit001","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986112,52.554699]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit002","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit003","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit004","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390311,52.507522]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit005","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390309,52.50751]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
  	{
  		"id":"urn:ngsi-ld:Shelf:unit006","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447112,52.503199]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit007","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit008","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit009","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.444711,52.503122]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit010","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4094111,52.5208028]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"}
  	}
  ]
}'

#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id":"urn:ngsi-ld:Product:001", "type":"Product",
      "name":{"type":"Text", "value":"Tortilla Española"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 300}
    },
    {
      "id":"urn:ngsi-ld:Product:002", "type":"Product",
      "name":{"type":"Text", "value":"Café con Leche"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 150}
    },
    {
      "id":"urn:ngsi-ld:Product:003", "type":"Product",
      "name":{"type":"Text", "value":"Croissant"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 200}
    },
    {
      "id":"urn:ngsi-ld:Product:004", "type":"Product",
      "name":{"type":"Text", "value":"Churros con Chocolate"},
      "size":{"type":"Text", "value": "L"},
      "price":{"type":"Integer", "value": 400}
    },
    {
      "id":"urn:ngsi-ld:Product:005", "type":"Product",
      "name":{"type":"Text", "value":"Zumo de Naranja"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 250}
    },
    {
      "id":"urn:ngsi-ld:Product:006", "type":"Product",
      "name":{"type":"Text", "value":"Bocadillo de Jamón"},
      "size":{"type":"Text", "value": "L"},
      "price":{"type":"Integer", "value": 500}
    },
    {
      "id":"urn:ngsi-ld:Product:007", "type":"Product",
      "name":{"type":"Text", "value":"Ensaladilla Rusa"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 350}
    },
    {
      "id":"urn:ngsi-ld:Product:008", "type":"Product",
      "name":{"type":"Text", "value":"Tostada con Tomate"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 200}
    },
    {
      "id":"urn:ngsi-ld:Product:009", "type":"Product",
      "name":{"type":"Text", "value":"Caña de Cerveza"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 250}
    },
    {
      "id":"urn:ngsi-ld:Product:010", "type":"Product",
      "name":{"type":"Text", "value":"Café Cortado"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 150}
    }
  ]
}'


#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:001
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:001","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit001"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:002","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit002"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:003"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:003","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit003"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:004"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:002
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:004","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit004"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:005","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit005"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:002"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:003
# Note that Shelf Unit009 is currently unused
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:006","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit006"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:007","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit007"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:008"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:008","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit008"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:009"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:004
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:401","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit010"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'

#
# Ensure that actuators are minimally provisioned.

#!/bin/bash"

# Update Store Entities and their associated devices
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
    "actionType": "append",
    "entities": [
      {
        "id": "urn:ngsi-ld:Bell:001",
        "type": "Alert",
        "name": { "type": "Text", "value": "New Customer Alert" },
        "state": { "type": "Text", "value": "quiet" }
      },
      {
        "id": "urn:ngsi-ld:Door:001",
        "type": "Toilet",
        "name": { "type": "Text", "value": "Toilet Door" },
        "state": { "type": "Text", "value": "free" }
      },
      {
        "id": "urn:ngsi-ld:Lamp:001",
        "type": "Light",
        "name": { "type": "Text", "value": "Main Entrance Lights" },
        "state": { "type": "Text", "value": "off" }
      }
    ]
}'

#
curl -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id": "Bell:001",
      "type": "Bell",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:001"
      }
    },
    {
      "id": "Door:001",
      "type": "Door",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:001"
      }
    }, 
    {
      "id": "Lamp:001",
      "type": "Lamp",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:001"
      }
    },
    {
      "id": "Temperature:001",
      "type": "TemperatureSensor",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:001"
      }
    },
    {
      "id": "Bell:002",
      "type": "Bell",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:002"
      }
    },
    {
      "id": "Door:002",
      "type": "Door",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:002"
      }
    }, 
    {
      "id": "Lamp:002",
      "type": "Lamp",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:002"
      }
    },
    {
      "id": "Temperature:002",
      "type": "TemperatureSensor",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:002"
      }
    },
    {
      "id": "Bell:003",
      "type": "Bell",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:003"
      }
    },
    {
      "id": "Door:003",
      "type": "Door",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:003"
      }
    }, 
    {
      "id": "Lamp:003",
      "type": "Lamp",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:003"
      }
    },
    {
      "id": "Temperature:003",
      "type": "TemperatureSensor",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:003"
      }
    },
    {
      "id": "Bell:004",
      "type": "Bell",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:004"
      }
    },
    {
      "id": "Door:004",
      "type": "Door",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:004"
      }
    }, 
    {
      "id": "Temperature:004",
      "type": "TemperatureSensor",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:004"
      }
    },
    {
      "id": "Lamp:004",
      "type": "Lamp",
      "refStore": {
        "type": "Relationship","value": "urn:ngsi-ld:Store:004"
      }
    }
  ]
}'  

echo -e " \033[1;32mdone\033[0m"